#cloud-config
packages:
  - mariadb105-server

runcmd:
  - systemctl start mariadb
  - systemctl enable mariadb
  - echo "[mysqld]" >> /etc/my.cnf
  - echo "bind-address = 0.0.0.0" >> /etc/my.cnf
  - systemctl restart mariadb
